import { defineKind } from '../core/types'

export const area = defineKind({
  kind: 'area',
  baseUnit: 'm2',
  units: [
    {
      id: 'mm2',
      symbol: 'mm²',
      name: 'square millimeter',
      aliases: ['mm^2', 'sq mm', 'sq. mm.', 'square millimetre', 'square millimetres'],
      factor: 1e-6,
      system: 'metric',
    },
    {
      id: 'cm2',
      symbol: 'cm²',
      name: 'square centimeter',
      aliases: ['cm^2', 'sq cm', 'sq. cm.', 'square centimetre', 'square centimetres'],
      factor: 0.0001,
      system: 'metric',
      best: 0,
    },
    {
      id: 'm2',
      symbol: 'm²',
      name: 'square meter',
      aliases: ['m^2', 'sq m', 'sq. m.', 'sqm', 'square metre', 'square metres'],
      factor: 1,
      system: 'metric',
      best: 1,
    },
    {
      id: 'are',
      symbol: 'are',
      name: 'are',
      factor: 100,
      system: 'metric',
    },
    {
      id: 'ha',
      symbol: 'ha',
      name: 'hectare',
      factor: 10_000,
      system: 'metric',
      intl: 'hectare',
      best: 2,
    },
    {
      id: 'km2',
      symbol: 'km²',
      name: 'square kilometer',
      aliases: ['km^2', 'sq km', 'sq. km.', 'square kilometre', 'square kilometres'],
      factor: 1_000_000,
      system: 'metric',
      best: 3,
    },
    {
      id: 'in2',
      symbol: 'in²',
      name: 'square inch',
      plural: 'square inches',
      aliases: ['in^2', 'sq in', 'sq. in.'],
      factor: 0.0254 * 0.0254,
      system: 'imperial',
    },
    {
      id: 'ft2',
      symbol: 'ft²',
      name: 'square foot',
      plural: 'square feet',
      aliases: ['ft^2', 'sq ft', 'sq. ft.', 'sqft', 'sf', 'square ft'],
      factor: 0.3048 * 0.3048,
      system: 'imperial',
      best: 0,
    },
    {
      id: 'yd2',
      symbol: 'yd²',
      name: 'square yard',
      aliases: ['yd^2', 'sq yd', 'sq. yd.'],
      factor: 0.9144 * 0.9144,
      system: 'imperial',
    },
    {
      id: 'ac',
      symbol: 'ac',
      name: 'acre',
      factor: 4046.856_422_4,
      system: 'us',
      intl: 'acre',
      best: 1,
    },
    {
      id: 'mi2',
      symbol: 'mi²',
      name: 'square mile',
      aliases: ['mi^2', 'sq mi', 'sq. mi.'],
      factor: 1609.344 * 1609.344,
      system: 'imperial',
      best: 2,
    },
  ],
} as const)

// Deliberately no bare "a" alias for are; it is too ambiguous in prose.
