import { defineKind } from '../core/types'

export const charge = defineKind({
  kind: 'charge',
  baseUnit: 'C',
  units: [
    {
      id: 'μC',
      symbol: 'μC',
      name: 'microcoulomb',
      aliases: ['microcoulombs'],
      caseExact: ['μC', 'uC'],
      factor: 1e-6,
      system: 'shared',
      best: 0,
    },
    {
      id: 'mC',
      symbol: 'mC',
      name: 'millicoulomb',
      aliases: ['millicoulombs'],
      caseExact: ['mC'],
      factor: 1e-3,
      system: 'shared',
      best: 1,
    },
    {
      id: 'C',
      symbol: 'C',
      name: 'coulomb',
      aliases: ['coulombs'],
      factor: 1,
      system: 'shared',
      best: 2,
    },
    {
      id: 'kC',
      symbol: 'kC',
      name: 'kilocoulomb',
      aliases: ['kilocoulombs'],
      factor: 1000,
      system: 'shared',
      best: 3,
    },
    {
      id: 'mAh',
      symbol: 'mAh',
      name: 'milliampere hour',
      aliases: ['milliamp hour', 'milliamp hours', 'milliampere hours'],
      caseExact: ['mAh', 'mah'],
      factor: 3.6,
      system: 'shared',
    },
    {
      id: 'Ah',
      symbol: 'Ah',
      name: 'ampere hour',
      aliases: ['amp hour', 'amp hours', 'ampere hours'],
      caseExact: ['Ah'],
      factor: 3600,
      system: 'shared',
    },
  ],
} as const)
