import { defineKind } from '../core/types'

export const concentration = defineKind({
  kind: 'concentration',
  baseUnit: 'mol/m3',
  units: [
    {
      id: 'mol/m3',
      symbol: 'mol/m³',
      name: 'mole per cubic meter',
      plural: 'moles per cubic meter',
      aliases: ['mol/m^3'],
      factor: 1,
      system: 'metric',
      best: 0,
    },
    {
      id: 'M',
      symbol: 'M',
      name: 'molar',
      plural: 'molar',
      caseExact: ['M'],
      factor: 1000,
      system: 'metric',
      best: 3,
    },
    {
      id: 'mM',
      symbol: 'mM',
      name: 'millimolar',
      plural: 'millimolar',
      caseExact: ['mM'],
      factor: 1,
      system: 'metric',
      best: 2,
    },
    {
      id: 'μM',
      symbol: 'μM',
      name: 'micromolar',
      plural: 'micromolar',
      caseExact: ['μM', 'µM', 'uM'],
      factor: 1e-3,
      system: 'metric',
      best: 1,
    },
    {
      id: 'nM',
      symbol: 'nM',
      name: 'nanomolar',
      plural: 'nanomolar',
      caseExact: ['nM'],
      factor: 1e-6,
      system: 'metric',
      best: 0,
    },
    {
      id: 'pM',
      symbol: 'pM',
      name: 'picomolar',
      plural: 'picomolar',
      caseExact: ['pM'],
      factor: 1e-9,
      system: 'metric',
    },
    {
      id: 'mol/l',
      symbol: 'mol/L',
      name: 'mole per liter',
      plural: 'moles per liter',
      aliases: ['mol / L', 'mol/liter', 'mol/litre', 'mol per L', 'mol per liter', 'mol per litre'],
      factor: 1000,
      system: 'metric',
    },
    {
      id: 'mmol/l',
      symbol: 'mmol/L',
      name: 'millimole per liter',
      plural: 'millimoles per liter',
      aliases: [
        'mmol / L',
        'mmol/liter',
        'mmol/litre',
        'mmol per L',
        'mmol per liter',
        'mmol per litre',
      ],
      factor: 1,
      system: 'metric',
    },
    {
      id: 'μmol/l',
      symbol: 'μmol/L',
      name: 'micromole per liter',
      plural: 'micromoles per liter',
      aliases: [
        'µmol/L',
        'umol/L',
        'µmol / L',
        'umol / L',
        'μmol / L',
        'umol/liter',
        'umol/litre',
        'μmol/liter',
        'μmol/litre',
        'µmol per L',
        'µmol per liter',
        'µmol per litre',
        'umol per L',
        'umol per liter',
        'umol per litre',
        'μmol per L',
        'μmol per liter',
        'μmol per litre',
      ],
      factor: 1e-3,
      system: 'metric',
    },
  ],
} as const)

// Concentration covers declared chemistry amount-per-volume units only.
