import { defineKind } from '../core/types'

export const currency = defineKind({
  kind: 'currency',
  baseUnit: 'USD',
  rateBased: true,
  units: [
    {
      id: 'USD',
      symbol: '$',
      name: 'dollar',
      plural: 'dollars',
      aliases: [
        'usd',
        'us dollar',
        'us dollars',
        'united states dollar',
        'united states dollars',
        'bucks',
      ],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'EUR',
      symbol: '€',
      name: 'euro',
      plural: 'euros',
      aliases: ['eur', 'euros'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'GBP',
      symbol: '£',
      name: 'pound sterling',
      plural: 'pounds sterling',
      aliases: ['gbp', 'british pound', 'british pounds', 'sterling', 'quid'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'JPY',
      symbol: '¥',
      name: 'yen',
      plural: 'yen',
      aliases: ['jpy', 'japanese yen'],
      factor: 1,
      minorUnit: 0,
      system: 'shared',
    },
    {
      id: 'CHF',
      symbol: 'CHF',
      name: 'Swiss franc',
      plural: 'Swiss francs',
      aliases: ['chf'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'CAD',
      symbol: 'CA$',
      name: 'Canadian dollar',
      plural: 'Canadian dollars',
      aliases: ['cad'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'AUD',
      symbol: 'A$',
      name: 'Australian dollar',
      plural: 'Australian dollars',
      aliases: ['aud'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'CNY',
      symbol: 'CN¥',
      name: 'yuan',
      plural: 'yuan',
      aliases: ['cny', 'renminbi', 'chinese yuan'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'INR',
      symbol: '₹',
      name: 'rupee',
      plural: 'rupees',
      aliases: ['inr', 'indian rupee', 'indian rupees'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'KRW',
      symbol: '₩',
      name: 'won',
      plural: 'won',
      aliases: ['krw', 'korean won', 'south korean won'],
      factor: 1,
      minorUnit: 0,
      system: 'shared',
    },
    {
      id: 'SGD',
      symbol: 'S$',
      name: 'Singapore dollar',
      plural: 'Singapore dollars',
      aliases: ['sgd'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'HKD',
      symbol: 'HK$',
      name: 'Hong Kong dollar',
      plural: 'Hong Kong dollars',
      aliases: ['hkd'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'NZD',
      symbol: 'NZ$',
      name: 'New Zealand dollar',
      plural: 'New Zealand dollars',
      aliases: ['nzd'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'MXN',
      symbol: 'MX$',
      name: 'Mexican peso',
      plural: 'Mexican pesos',
      aliases: ['mxn', 'peso', 'pesos'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'BRL',
      symbol: 'R$',
      name: 'Brazilian real',
      plural: 'Brazilian reals',
      aliases: ['brl', 'reais'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'ZAR',
      symbol: 'R',
      name: 'South African rand',
      plural: 'South African rand',
      aliases: ['zar', 'rand', 'rands'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'SEK',
      symbol: 'SEK',
      name: 'Swedish krona',
      plural: 'Swedish kronor',
      aliases: ['sek', 'krona', 'kronor'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'NOK',
      symbol: 'NOK',
      name: 'Norwegian krone',
      plural: 'Norwegian kroner',
      aliases: ['nok', 'krone', 'kroner'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'DKK',
      symbol: 'DKK',
      name: 'Danish krone',
      plural: 'Danish kroner',
      aliases: ['dkk'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'PLN',
      symbol: 'zł',
      name: 'zloty',
      plural: 'zloty',
      aliases: ['pln', 'złoty'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'CZK',
      symbol: 'Kč',
      name: 'Czech koruna',
      plural: 'Czech koruny',
      aliases: ['czk', 'koruna', 'koruny'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'HUF',
      symbol: 'HUF',
      name: 'forint',
      plural: 'forints',
      aliases: ['huf'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'TRY',
      symbol: '₺',
      name: 'Turkish lira',
      plural: 'Turkish lira',
      aliases: ['try', 'lira'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'ILS',
      symbol: '₪',
      name: 'shekel',
      plural: 'shekels',
      aliases: ['ils', 'israeli shekel', 'israeli shekels'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'AED',
      symbol: 'AED',
      name: 'UAE dirham',
      plural: 'UAE dirhams',
      aliases: ['aed', 'dirham', 'dirhams'],
      factor: 1,
      minorUnit: 2,
      system: 'shared',
    },
    {
      id: 'KWD',
      symbol: 'KWD',
      name: 'Kuwaiti dinar',
      plural: 'Kuwaiti dinars',
      aliases: ['kwd', 'kuwaiti dinar', 'kuwaiti dinars'],
      factor: 1,
      minorUnit: 3,
      system: 'shared',
    },
    {
      id: 'BHD',
      symbol: 'BHD',
      name: 'Bahraini dinar',
      plural: 'Bahraini dinars',
      aliases: ['bhd', 'bahraini dinar', 'bahraini dinars'],
      factor: 1,
      minorUnit: 3,
      system: 'shared',
    },
    {
      id: 'OMR',
      symbol: 'OMR',
      name: 'Omani rial',
      plural: 'Omani rials',
      aliases: ['omr', 'omani rial', 'omani rials'],
      factor: 1,
      minorUnit: 3,
      system: 'shared',
    },
  ],
} as const)
