import { defineKind } from '../core/types'

export const data = defineKind({
  kind: 'data',
  baseUnit: 'B',
  units: [
    {
      id: 'bit',
      symbol: 'bit',
      name: 'bit',
      factor: 0.125,
      system: 'shared',
      caseExact: ['b'],
      intl: 'bit',
    },
    {
      id: 'B',
      symbol: 'B',
      name: 'byte',
      factor: 1,
      system: 'shared',
      caseExact: ['B'],
      intl: 'byte',
      best: 0,
    },
    {
      id: 'kbit',
      symbol: 'kbit',
      name: 'kilobit',
      factor: 125,
      system: 'shared',
      caseExact: ['Kb'],
      intl: 'kilobit',
    },
    {
      id: 'Mbit',
      symbol: 'Mbit',
      name: 'megabit',
      factor: 1.25e5,
      system: 'shared',
      caseExact: ['Mb'],
      intl: 'megabit',
    },
    {
      id: 'Gbit',
      symbol: 'Gbit',
      name: 'gigabit',
      factor: 1.25e8,
      system: 'shared',
      caseExact: ['Gb'],
      intl: 'gigabit',
    },
    {
      id: 'Tbit',
      symbol: 'Tbit',
      name: 'terabit',
      factor: 1.25e11,
      system: 'shared',
      caseExact: ['Tb'],
      intl: 'terabit',
    },
    {
      id: 'kB',
      symbol: 'kB',
      name: 'kilobyte',
      factor: 1e3,
      system: 'shared',
      caseExact: ['KB', 'kB'],
      intl: 'kilobyte',
      best: 1,
    },
    {
      id: 'MB',
      symbol: 'MB',
      name: 'megabyte',
      factor: 1e6,
      system: 'shared',
      caseExact: ['MB'],
      intl: 'megabyte',
      best: 2,
    },
    {
      id: 'GB',
      symbol: 'GB',
      name: 'gigabyte',
      factor: 1e9,
      system: 'shared',
      aliases: ['gig', 'gigs'],
      caseExact: ['GB'],
      intl: 'gigabyte',
      best: 3,
    },
    {
      id: 'TB',
      symbol: 'TB',
      name: 'terabyte',
      factor: 1e12,
      system: 'shared',
      caseExact: ['TB'],
      intl: 'terabyte',
      best: 4,
    },
    {
      id: 'PB',
      symbol: 'PB',
      name: 'petabyte',
      factor: 1e15,
      system: 'shared',
      caseExact: ['PB'],
      intl: 'petabyte',
    },
    {
      id: 'KiB',
      symbol: 'KiB',
      name: 'kibibyte',
      factor: 1024,
      system: 'shared',
      caseExact: ['KiB'],
      best: 0,
    },
    {
      id: 'MiB',
      symbol: 'MiB',
      name: 'mebibyte',
      factor: 1024 ** 2,
      system: 'shared',
      caseExact: ['MiB'],
      best: 1,
    },
    {
      id: 'GiB',
      symbol: 'GiB',
      name: 'gibibyte',
      factor: 1024 ** 3,
      system: 'shared',
      caseExact: ['GiB'],
      best: 2,
    },
    {
      id: 'TiB',
      symbol: 'TiB',
      name: 'tebibyte',
      factor: 1024 ** 4,
      system: 'shared',
      caseExact: ['TiB'],
      best: 3,
    },
    {
      id: 'PiB',
      symbol: 'PiB',
      name: 'pebibyte',
      factor: 1024 ** 5,
      system: 'shared',
      caseExact: ['PiB'],
    },
  ],
} as const)

// Deliberately no lowercase "kb"/"mb"/"gb"/"tb" aliases, no "bps"/"basis points",
// and no JEDEC-style 1024-based "KB"; kB/KB are decimal and KiB is binary.
