import { defineKind } from '../core/types'

export const duration = defineKind({
  kind: 'duration',
  baseUnit: 's',
  units: [
    {
      id: 'ns',
      symbol: 'ns',
      name: 'nanosecond',
      factor: 1e-9,
      system: 'shared',
      intl: 'nanosecond',
    },
    {
      id: 'μs',
      symbol: 'μs',
      name: 'microsecond',
      aliases: ['µs', 'μs', 'usec'],
      factor: 1e-6,
      system: 'shared',
      intl: 'microsecond',
    },
    {
      id: 'ms',
      symbol: 'ms',
      name: 'millisecond',
      aliases: ['msec', 'msecs'],
      factor: 1e-3,
      system: 'shared',
      intl: 'millisecond',
      best: 0,
    },
    {
      id: 's',
      symbol: 's',
      name: 'second',
      aliases: ['sec', 'secs'],
      factor: 1,
      system: 'shared',
      subunit: { unit: 'ms', per: 1000 },
      intl: 'second',
      best: 1,
    },
    {
      id: 'min',
      symbol: 'min',
      name: 'minute',
      aliases: ['mins'],
      factor: 60,
      system: 'shared',
      subunit: { unit: 's', per: 60 },
      intl: 'minute',
      best: 2,
    },
    {
      id: 'h',
      symbol: 'h',
      name: 'hour',
      aliases: ['hr', 'hrs'],
      factor: 3600,
      system: 'shared',
      subunit: { unit: 'min', per: 60 },
      intl: 'hour',
      best: 3,
    },
    {
      id: 'd',
      symbol: 'd',
      name: 'day',
      factor: 86_400,
      system: 'shared',
      subunit: { unit: 'h', per: 24 },
      intl: 'day',
      best: 4,
    },
    {
      id: 'wk',
      symbol: 'wk',
      name: 'week',
      aliases: ['wks'],
      factor: 604_800,
      system: 'shared',
      subunit: { unit: 'd', per: 7 },
      intl: 'week',
      best: 5,
    },
    {
      id: 'fortnight',
      symbol: 'fortnight',
      name: 'fortnight',
      factor: 1_209_600,
      system: 'shared',
    },
    {
      id: 'mo',
      symbol: 'mo',
      name: 'month',
      aliases: ['mos'],
      factor: 2_629_800,
      system: 'shared',
      intl: 'month',
      best: 6,
    },
    {
      id: 'yr',
      symbol: 'yr',
      name: 'year',
      aliases: ['yrs', 'annum'],
      factor: 31_557_600,
      system: 'shared',
      subunit: { unit: 'mo', per: 12 },
      intl: 'year',
      best: 7,
    },
    {
      id: 'decade',
      symbol: 'decade',
      name: 'decade',
      factor: 315_576_000,
      system: 'shared',
    },
    {
      id: 'century',
      symbol: 'century',
      name: 'century',
      plural: 'centuries',
      factor: 3_155_760_000,
      system: 'shared',
    },
  ],
} as const)

// Month and year durations use the Julian/UCUM convention: 30.4375 d and 365.25 d.
// Deliberately no bare "us" microsecond alias; it is ambiguous prose, so "usec" is the ASCII fallback.
