import { defineKind } from '../core/types'

const US_GALLON = 0.003_785_411_784
const IMPERIAL_GALLON = 0.004_546_09
const CUBIC_FOOT = 0.3048 ** 3

export const flowRate = defineKind({
  kind: 'flow_rate',
  baseUnit: 'm3/s',
  units: [
    {
      id: 'm3/s',
      symbol: 'm³/s',
      name: 'cubic meter per second',
      plural: 'cubic meters per second',
      aliases: ['m^3/s', 'm3/sec', 'm^3/sec', 'cubic metre per second', 'cubic metres per second'],
      factor: 1,
      system: 'metric',
      best: 3,
    },
    {
      id: 'm3/h',
      symbol: 'm³/h',
      name: 'cubic meter per hour',
      plural: 'cubic meters per hour',
      aliases: [
        'm^3/h',
        'm3/hr',
        'm^3/hr',
        'm3/hour',
        'm^3/hour',
        'm3 per hour',
        'm^3 per hour',
        'cubic meter per hr',
        'cubic meters per hr',
        'cubic metre per hour',
        'cubic metres per hour',
      ],
      factor: 1 / 3600,
      system: 'metric',
      best: 2,
    },
    {
      id: 'l/s',
      symbol: 'L/s',
      name: 'liter per second',
      plural: 'liters per second',
      aliases: [
        'l/sec',
        'l per s',
        'l per sec',
        'l per second',
        'l / s',
        'liter/s',
        'liters/s',
        'liter per sec',
        'liters per sec',
        'liter a second',
        'liters a second',
        'litre/s',
        'litres/s',
        'litre per second',
        'litres per second',
        'litre a second',
        'litres a second',
      ],
      factor: 0.001,
      system: 'metric',
      best: 1,
    },
    {
      id: 'l/min',
      symbol: 'L/min',
      name: 'liter per minute',
      plural: 'liters per minute',
      aliases: [
        'lpm',
        'l per min',
        'l per minute',
        'l / min',
        'liter per min',
        'liters per min',
        'litre per minute',
        'litres per minute',
        'litre per min',
        'litres per min',
      ],
      factor: 0.001 / 60,
      system: 'metric',
      best: 0,
    },
    {
      id: 'l/h',
      symbol: 'L/h',
      name: 'liter per hour',
      plural: 'liters per hour',
      aliases: ['l/hr', 'liter/hour', 'liters/hour', 'litre per hour', 'litres per hour'],
      factor: 0.001 / 3600,
      system: 'metric',
    },
    {
      id: 'ml/s',
      symbol: 'mL/s',
      name: 'milliliter per second',
      plural: 'milliliters per second',
      aliases: [
        'milliliter per sec',
        'milliliters per sec',
        'millilitre per second',
        'millilitres per second',
        'cc/s',
        'cc/sec',
      ],
      caseExact: ['ml/s', 'mL/s', 'ml/sec', 'mL/sec', 'ml per s', 'mL per s'],
      factor: 1e-6,
      system: 'metric',
    },
    {
      id: 'ml/min',
      symbol: 'mL/min',
      name: 'milliliter per minute',
      plural: 'milliliters per minute',
      aliases: [
        'milliliter per min',
        'milliliters per min',
        'millilitre per minute',
        'millilitres per minute',
        'cc/min',
        'cc/minute',
        'cc per minute',
      ],
      caseExact: [
        'ml/min',
        'mL/min',
        'ml/minute',
        'mL/minute',
        'ml per min',
        'mL per min',
        'ml per minute',
        'mL per minute',
        'ml / min',
        'mL / min',
      ],
      factor: 1e-6 / 60,
      system: 'metric',
    },
    {
      id: 'gal/min',
      symbol: 'gal/min',
      name: 'gallon per minute',
      plural: 'gallons per minute',
      aliases: ['gpm', 'gal/minute', 'gallon/min', 'gallons/min'],
      factor: US_GALLON / 60,
      system: 'us',
      best: 0,
    },
    {
      id: 'gal-imp/min',
      symbol: 'imp gal/min',
      name: 'imperial gallon per minute',
      plural: 'imperial gallons per minute',
      aliases: ['imperial gpm', 'imp gpm', 'imp gal/minute'],
      factor: IMPERIAL_GALLON / 60,
      system: 'imperial',
    },
    {
      id: 'ft3/min',
      symbol: 'ft³/min',
      name: 'cubic foot per minute',
      plural: 'cubic feet per minute',
      aliases: [
        'cfm',
        'ft^3/min',
        'cu ft/min',
        'cu ft per min',
        'cu ft per minute',
        'cubic foot/min',
        'cubic feet/min',
        'cubic feet per min',
      ],
      factor: CUBIC_FOOT / 60,
      system: 'us',
      best: 1,
    },
    {
      id: 'ft3/s',
      symbol: 'ft³/s',
      name: 'cubic foot per second',
      plural: 'cubic feet per second',
      aliases: ['cfs', 'ft^3/s', 'cu ft/s', 'cubic ft per second'],
      factor: CUBIC_FOOT,
      system: 'us',
      best: 2,
    },
  ],
} as const)

// Flow rates are declarative quotient units; arbitrary unit algebra stays out of scope.
