import { defineKind } from '../core/types'

export const force = defineKind({
  kind: 'force',
  baseUnit: 'N',
  units: [
    {
      id: 'μN',
      symbol: 'μN',
      name: 'micronewton',
      factor: 1e-6,
      system: 'shared',
      best: 0,
    },
    {
      id: 'mN',
      symbol: 'mN',
      name: 'millinewton',
      factor: 1e-3,
      system: 'shared',
      caseExact: ['mN'],
      best: 1,
    },
    {
      id: 'N',
      symbol: 'N',
      name: 'newton',
      factor: 1,
      system: 'shared',
      best: 2,
    },
    {
      id: 'kN',
      symbol: 'kN',
      name: 'kilonewton',
      factor: 1000,
      system: 'shared',
      caseExact: ['kN'],
      best: 3,
    },
    {
      id: 'MN',
      symbol: 'MN',
      name: 'meganewton',
      factor: 1e6,
      system: 'shared',
      caseExact: ['MN'],
      best: 4,
    },
    {
      id: 'dyn',
      symbol: 'dyn',
      name: 'dyne',
      factor: 1e-5,
      system: 'shared',
    },
    {
      id: 'lbf',
      symbol: 'lbf',
      name: 'pound-force',
      plural: 'pounds-force',
      aliases: ['pound force', 'pounds force'],
      factor: 4.448_221_615_260_5,
      system: 'imperial',
    },
    {
      id: 'kgf',
      symbol: 'kgf',
      name: 'kilogram-force',
      plural: 'kilograms-force',
      aliases: ['kilogram force', 'kilograms force'],
      factor: 9.806_65,
      system: 'metric',
    },
  ],
} as const)
