import { defineKind } from '../core/types'

export const length = defineKind({
  kind: 'length',
  baseUnit: 'm',
  units: [
    {
      id: 'nm',
      symbol: 'nm',
      name: 'nanometer',
      aliases: ['nanometre', 'nanometres'],
      caseExact: ['nm'],
      factor: 1e-9,
      system: 'metric',
    },
    {
      id: 'μm',
      symbol: 'μm',
      name: 'micrometer',
      aliases: ['micrometre', 'micrometres', 'micron', 'microns'],
      caseExact: ['μm', 'um'],
      factor: 1e-6,
      system: 'metric',
    },
    {
      id: 'mm',
      symbol: 'mm',
      name: 'millimeter',
      aliases: ['millimetre', 'millimetres'],
      factor: 1e-3,
      system: 'metric',
      intl: 'millimeter',
      best: 0,
    },
    {
      id: 'cm',
      symbol: 'cm',
      name: 'centimeter',
      aliases: ['centimetre', 'centimetres'],
      factor: 0.01,
      system: 'metric',
      subunit: { unit: 'mm', per: 10 },
      intl: 'centimeter',
      best: 1,
    },
    {
      id: 'm',
      symbol: 'm',
      name: 'meter',
      aliases: ['metre', 'metres'],
      caseExact: ['m'],
      factor: 1,
      system: 'metric',
      subunit: { unit: 'cm', per: 100 },
      intl: 'meter',
      best: 2,
    },
    {
      id: 'km',
      symbol: 'km',
      name: 'kilometer',
      aliases: ['kilometre', 'kilometres', 'klick', 'klicks'],
      factor: 1000,
      system: 'metric',
      subunit: { unit: 'm', per: 1000 },
      intl: 'kilometer',
      best: 3,
    },
    {
      // Exact-case so `Mm` resolves to megameter, not millimeter (mm) — the
      // plans/003 hazard table names this collision by name. No `best` rank:
      // parse-only, never emitted by best-fit formatting.
      id: 'Mm',
      symbol: 'Mm',
      name: 'megameter',
      aliases: ['megametre', 'megametres'],
      caseExact: ['Mm'],
      factor: 1e6,
      system: 'metric',
    },
    {
      id: 'in',
      symbol: 'in',
      name: 'inch',
      plural: 'inches',
      aliases: ['in.', '"', '″', "''"],
      factor: 0.0254,
      system: 'imperial',
      intl: 'inch',
      best: 0,
    },
    {
      id: 'ft',
      symbol: 'ft',
      name: 'foot',
      plural: 'feet',
      aliases: ['ft.', "'", '′'],
      factor: 0.3048,
      system: 'imperial',
      subunit: { unit: 'in', per: 12 },
      intl: 'foot',
      best: 1,
    },
    {
      id: 'yd',
      symbol: 'yd',
      name: 'yard',
      aliases: ['yd.'],
      factor: 0.9144,
      system: 'imperial',
      intl: 'yard',
    },
    {
      id: 'mi',
      symbol: 'mi',
      name: 'mile',
      aliases: ['statute mile', 'statute miles'],
      factor: 1609.344,
      system: 'imperial',
      intl: 'mile',
      best: 2,
    },
    {
      id: 'nmi',
      symbol: 'nmi',
      name: 'nautical mile',
      factor: 1852,
      system: 'shared',
    },
    {
      id: 'ft-us',
      symbol: 'ft-us',
      name: 'US survey foot',
      plural: 'US survey feet',
      aliases: ['survey foot', 'survey feet', 'us survey foot', 'us survey feet'],
      factor: 1200 / 3937,
      system: 'us',
    },
    {
      id: 'fathom',
      symbol: 'fathom',
      name: 'fathom',
      factor: 1.8288,
      system: 'imperial',
    },
    {
      id: 'furlong',
      symbol: 'furlong',
      name: 'furlong',
      factor: 201.168,
      system: 'imperial',
    },
    {
      id: 'hand',
      symbol: 'hand',
      name: 'hand',
      factor: 0.1016,
      system: 'imperial',
    },
    {
      id: 'thou',
      symbol: 'thou',
      name: 'thou',
      aliases: ['thousandth of an inch', 'thousandths of an inch'],
      factor: 0.000_025_4,
      system: 'imperial',
    },
    {
      id: 'angstrom',
      symbol: 'Å',
      name: 'angstrom',
      aliases: ['ångström', 'ångströms'],
      factor: 1e-10,
      system: 'metric',
    },
    {
      id: 'au',
      symbol: 'au',
      name: 'astronomical unit',
      factor: 149_597_870_700,
      system: 'shared',
    },
    {
      id: 'ly',
      symbol: 'ly',
      name: 'light year',
      aliases: ['light-year', 'light-years'],
      factor: 9_460_730_472_580_800,
      system: 'shared',
    },
    {
      id: 'pc',
      symbol: 'pc',
      name: 'parsec',
      factor: (648_000 / Math.PI) * 149_597_870_700,
      system: 'shared',
    },
  ],
} as const)

// Deliberately no bare "pm" (ambiguous time token) or "mil" (mile prefix/thousandth ambiguity).
