import { defineKind } from '../core/types'

export const mass = defineKind({
  kind: 'mass',
  baseUnit: 'kg',
  units: [
    {
      id: 'μg',
      symbol: 'μg',
      name: 'microgram',
      aliases: ['microgramme', 'microgrammes', 'ug', 'mcg'],
      factor: 1e-9,
      system: 'metric',
    },
    {
      id: 'mg',
      symbol: 'mg',
      name: 'milligram',
      factor: 1e-6,
      system: 'metric',
      best: 0,
    },
    {
      id: 'g',
      symbol: 'g',
      name: 'gram',
      aliases: ['gramme', 'grammes'],
      factor: 0.001,
      system: 'metric',
      intl: 'gram',
      best: 1,
    },
    {
      id: 'kg',
      symbol: 'kg',
      name: 'kilogram',
      aliases: ['kilo', 'kilos', 'kgs', 'kilogramme', 'kilogrammes'],
      factor: 1,
      system: 'metric',
      intl: 'kilogram',
      best: 2,
    },
    {
      id: 't',
      symbol: 't',
      name: 'tonne',
      aliases: ['metric ton', 'metric tons'],
      factor: 1000,
      system: 'metric',
      best: 3,
    },
    {
      // Exact-case so `Mg` resolves to megagram, not milligram (mg): a bare
      // case-fold would silently misread it by 10^9. Same magnitude as tonne,
      // so no `best` rank — parse-only, never emitted by best-fit formatting.
      id: 'Mg',
      symbol: 'Mg',
      name: 'megagram',
      aliases: ['megagramme', 'megagrammes'],
      caseExact: ['Mg'],
      factor: 1000,
      system: 'metric',
    },
    {
      id: 'oz',
      symbol: 'oz',
      name: 'ounce',
      aliases: ['oz.'],
      factor: 0.453_592_37 / 16,
      system: 'imperial',
      intl: 'ounce',
      best: 0,
    },
    {
      id: 'lb',
      symbol: 'lb',
      name: 'pound',
      aliases: ['lb.', 'lbs', 'lbs.', '#'],
      factor: 0.453_592_37,
      system: 'imperial',
      subunit: { unit: 'oz', per: 16 },
      intl: 'pound',
      best: 1,
    },
    {
      id: 'st',
      symbol: 'st',
      name: 'stone',
      factor: 0.453_592_37 * 14,
      system: 'imperial',
      subunit: { unit: 'lb', per: 14 },
      intl: 'stone',
      best: 2,
    },
    {
      id: 'gr',
      symbol: 'gr',
      name: 'grain',
      factor: 0.000_064_798_91,
      system: 'imperial',
    },
    {
      id: 'ozt',
      symbol: 'ozt',
      name: 'troy ounce',
      aliases: ['ozt.', 'troy oz', 'troy oz.'],
      factor: 0.031_103_476_8,
      system: 'shared',
    },
    {
      id: 'ct',
      symbol: 'ct',
      name: 'carat',
      factor: 0.0002,
      system: 'metric',
    },
    {
      id: 'ton-short',
      symbol: 'ton',
      name: 'short ton',
      aliases: ['ton', 'tons', 'us ton', 'us tons'],
      factor: 907.184_74,
      system: 'us',
    },
    {
      id: 'ton-long',
      symbol: 'long ton',
      name: 'long ton',
      aliases: ['imperial ton', 'imperial tons'],
      factor: 1016.046_908_8,
      system: 'imperial',
    },
  ],
} as const)
