import { defineKind } from '../core/types'

export const power = defineKind({
  kind: 'power',
  baseUnit: 'W',
  units: [
    {
      id: 'mW',
      symbol: 'mW',
      name: 'milliwatt',
      factor: 1e-3,
      system: 'shared',
      caseExact: ['mW'],
      best: 0,
    },
    {
      id: 'W',
      symbol: 'W',
      name: 'watt',
      factor: 1,
      system: 'shared',
      best: 1,
    },
    {
      id: 'kW',
      symbol: 'kW',
      name: 'kilowatt',
      factor: 1000,
      system: 'shared',
      best: 2,
    },
    {
      id: 'MW',
      symbol: 'MW',
      name: 'megawatt',
      factor: 1e6,
      system: 'shared',
      caseExact: ['MW'],
      best: 3,
    },
    {
      id: 'GW',
      symbol: 'GW',
      name: 'gigawatt',
      factor: 1e9,
      system: 'shared',
      best: 4,
    },
    {
      id: 'hp',
      symbol: 'hp',
      name: 'horsepower',
      plural: 'horsepower',
      aliases: ['mechanical horsepower'],
      factor: 745.699_872,
      system: 'imperial',
    },
    {
      id: 'PS',
      symbol: 'PS',
      name: 'metric horsepower',
      plural: 'metric horsepower',
      factor: 735.498_75,
      system: 'metric',
    },
    {
      id: 'Btu/h',
      symbol: 'Btu/h',
      name: 'British thermal unit per hour',
      plural: 'British thermal units per hour',
      aliases: ['btu/hr', 'btu per hour', 'btus per hour'],
      factor: 0.293_071_07,
      system: 'imperial',
    },
  ],
} as const)
