import { defineKind } from '../core/types'

export const pressure = defineKind({
  kind: 'pressure',
  baseUnit: 'Pa',
  units: [
    {
      // Exact-case so `mPa` resolves to millipascal, not megapascal (MPa): a
      // bare case-fold would silently misread it by 10^9. Sloppy all-lowercase
      // `mpa` still reads as megapascal via the case-insensitive MPa alias.
      // No `best` rank — parse-only, never emitted by best-fit formatting.
      id: 'mPa',
      symbol: 'mPa',
      name: 'millipascal',
      caseExact: ['mPa'],
      factor: 1e-3,
      system: 'metric',
    },
    {
      id: 'Pa',
      symbol: 'Pa',
      name: 'pascal',
      factor: 1,
      system: 'metric',
      best: 0,
    },
    {
      id: 'hPa',
      symbol: 'hPa',
      name: 'hectopascal',
      factor: 100,
      system: 'metric',
    },
    {
      id: 'mbar',
      symbol: 'mbar',
      name: 'millibar',
      factor: 100,
      system: 'metric',
    },
    {
      id: 'kPa',
      symbol: 'kPa',
      name: 'kilopascal',
      factor: 1000,
      system: 'metric',
      best: 1,
    },
    {
      id: 'MPa',
      symbol: 'MPa',
      name: 'megapascal',
      factor: 1e6,
      system: 'metric',
    },
    {
      id: 'bar',
      symbol: 'bar',
      name: 'bar',
      factor: 1e5,
      system: 'metric',
      best: 2,
    },
    {
      // Exact-case so `Mbar` resolves to megabar, not millibar (mbar): a bare
      // case-fold would silently misread high-pressure physics values by 10^9.
      // No `best` rank — parse-only, never emitted by best-fit formatting.
      id: 'Mbar',
      symbol: 'Mbar',
      name: 'megabar',
      caseExact: ['Mbar'],
      factor: 1e11,
      system: 'metric',
    },
    {
      id: 'atm',
      symbol: 'atm',
      name: 'atmosphere',
      aliases: ['standard atmosphere', 'standard atmospheres'],
      factor: 101_325,
      system: 'shared',
    },
    {
      id: 'psi',
      symbol: 'psi',
      name: 'pound per square inch',
      plural: 'pounds per square inch',
      aliases: [
        'pound per sq inch',
        'pounds per sq inch',
        'lb per square inch',
        'lbs per square inch',
      ],
      factor: 6894.757_293_168,
      system: 'us',
      best: 0,
    },
    {
      id: 'mmHg',
      symbol: 'mmHg',
      name: 'millimeter of mercury',
      plural: 'millimeters of mercury',
      aliases: ['millimetre of mercury', 'millimetres of mercury'],
      factor: 133.322_387_415,
      system: 'shared',
    },
    {
      id: 'inHg',
      symbol: 'inHg',
      name: 'inch of mercury',
      plural: 'inches of mercury',
      factor: 3386.388_640_341,
      system: 'shared',
    },
    {
      id: 'cmH2O',
      symbol: 'cmH₂O',
      name: 'centimeter of water',
      plural: 'centimeters of water',
      aliases: ['cmH2O', 'cm H2O', 'cm water'],
      factor: 98.0665,
      system: 'shared',
    },
    {
      id: 'inH2O',
      symbol: 'inH₂O',
      name: 'inch of water',
      plural: 'inches of water',
      aliases: ['inH2O', 'in H2O', 'in water', 'iwc'],
      factor: 249.088_91,
      system: 'shared',
    },
    {
      id: 'mH2O',
      symbol: 'mH₂O',
      name: 'meter of water',
      plural: 'meters of water',
      aliases: ['mH2O', 'm H2O', 'm water'],
      factor: 9806.65,
      system: 'shared',
    },
    {
      id: 'kgf/cm2',
      symbol: 'kgf/cm²',
      name: 'kilogram-force per square centimeter',
      plural: 'kilogram-force per square centimeter',
      aliases: [
        'kgf/cm^2',
        'kgf/cm2',
        'kgf per square centimeter',
        'technical atmosphere',
        'technical atmospheres',
      ],
      factor: 98_066.5,
      system: 'metric',
    },
    {
      id: 'torr',
      symbol: 'Torr',
      name: 'torr',
      factor: 101_325 / 760,
      system: 'shared',
    },
  ],
} as const)
