import { defineKind } from '../core/types'

export const speed = defineKind({
  kind: 'speed',
  baseUnit: 'm/s',
  units: [
    {
      id: 'm/s',
      symbol: 'm/s',
      name: 'meter per second',
      plural: 'meters per second',
      aliases: [
        'mps',
        'm/sec',
        'metre per second',
        'metres per second',
        'meter a second',
        'meters a second',
        'meter/sec',
        'meters/sec',
      ],
      factor: 1,
      system: 'metric',
      best: 0,
    },
    {
      id: 'km/h',
      symbol: 'km/h',
      name: 'kilometer per hour',
      plural: 'kilometers per hour',
      aliases: [
        'km/hr',
        'kmh',
        'kmph',
        'kph',
        'kilometre per hour',
        'kilometres per hour',
        'kilometers an hour',
      ],
      factor: 1000 / 3600,
      system: 'metric',
      intl: 'kilometer-per-hour',
      best: 1,
    },
    {
      id: 'mph',
      symbol: 'mph',
      name: 'mile per hour',
      plural: 'miles per hour',
      aliases: [
        'mi/h',
        'mi/hr',
        'mi/hour',
        'mile an hour',
        'miles an hour',
        'mile/hour',
        'miles/hour',
      ],
      factor: 1609.344 / 3600,
      system: 'us',
      intl: 'mile-per-hour',
      best: 0,
    },
    {
      id: 'kn',
      symbol: 'kn',
      name: 'knot',
      aliases: ['kt', 'kts'],
      factor: 1852 / 3600,
      system: 'shared',
    },
    {
      id: 'ft/s',
      symbol: 'ft/s',
      name: 'foot per second',
      plural: 'feet per second',
      aliases: ['ft/sec', 'fps'],
      factor: 0.3048,
      system: 'imperial',
    },
  ],
} as const)

// Deliberately no pace units such as "min/km"; speed keeps quotient units only in v0.1.
