import { defineKind } from '../core/types'

export const temperature = defineKind({
  kind: 'temperature',
  baseUnit: 'K',
  units: [
    {
      id: 'K',
      symbol: 'K',
      name: 'kelvin',
      factor: 1,
      offset: 0,
      system: 'metric',
    },
    {
      id: 'C',
      symbol: '°C',
      name: 'degree Celsius',
      plural: 'degrees Celsius',
      aliases: [
        '°c',
        '° c',
        '℃',
        'ºc',
        'º c',
        'deg c',
        'degrees c',
        'degree celsius',
        'degrees celsius',
        'celsius',
        'centigrade',
      ],
      factor: 1,
      offset: 273.15,
      system: 'metric',
      intl: 'celsius',
    },
    {
      id: 'F',
      symbol: '°F',
      name: 'degree Fahrenheit',
      plural: 'degrees Fahrenheit',
      aliases: [
        '°f',
        '° f',
        '℉',
        'ºf',
        'º f',
        'deg f',
        'degrees f',
        'degree fahrenheit',
        'degrees fahrenheit',
        'fahrenheit',
      ],
      factor: 5 / 9,
      offset: 273.15 - (32 * 5) / 9,
      system: 'us',
      intl: 'fahrenheit',
    },
    {
      id: 'R',
      symbol: '°R',
      name: 'degree Rankine',
      plural: 'degrees Rankine',
      aliases: ['°r', '° r', 'deg r', 'degrees r', 'degree rankine', 'degrees rankine', 'rankine'],
      factor: 5 / 9,
      offset: 0,
      system: 'us',
    },
  ],
} as const)
