import { defineKind } from '../core/types'

const US_GALLON = 0.003_785_411_784
const IMPERIAL_GALLON = 0.004_546_09
const CUBIC_FOOT = 0.3048 ** 3

export const volume = defineKind({
  kind: 'volume',
  baseUnit: 'm3',
  units: [
    {
      id: 'ul',
      symbol: 'µL',
      name: 'microliter',
      aliases: ['μl'],
      factor: 1e-9,
      system: 'metric',
    },
    {
      id: 'ml',
      symbol: 'mL',
      name: 'milliliter',
      aliases: ['millilitre', 'millilitres'],
      factor: 1e-6,
      system: 'metric',
      intl: 'milliliter',
      best: 0,
    },
    {
      id: 'cl',
      symbol: 'cL',
      name: 'centiliter',
      factor: 1e-5,
      system: 'metric',
    },
    {
      id: 'dl',
      symbol: 'dL',
      name: 'deciliter',
      factor: 1e-4,
      system: 'metric',
    },
    {
      id: 'l',
      symbol: 'L',
      name: 'liter',
      aliases: ['litre', 'litres', 'ltr'],
      factor: 0.001,
      system: 'metric',
      intl: 'liter',
      best: 1,
    },
    // No megaliter unit: its only symbol `ML` is also the common casual
    // spelling of milliliter ("250 ML of water"), so registering it would make
    // the FAR more frequent milliliter input silently read 10^9 too large.
    // Unlike Mg/Mm/mHz (unambiguous mixed-case), the ML/mL collision has no safe
    // default, so megaliter stays out until an explicit disambiguation lands.
    {
      id: 'cm3',
      symbol: 'cm³',
      name: 'cubic centimeter',
      aliases: ['cc', 'cm^3', 'cubic centimetre', 'cubic centimetres'],
      factor: 1e-6,
      system: 'metric',
    },
    {
      id: 'm3',
      symbol: 'm³',
      name: 'cubic meter',
      aliases: ['m^3', 'cu m', 'cubic metre', 'cubic metres', 'cbm', 'cum'],
      factor: 1,
      system: 'metric',
      best: 2,
    },
    {
      id: 'ft3',
      symbol: 'ft³',
      name: 'cubic foot',
      plural: 'cubic feet',
      aliases: ['ft^3', 'cu ft', 'cu. ft.', 'cubic ft', 'cubic feet'],
      factor: CUBIC_FOOT,
      system: 'us',
    },
    {
      id: 'tsp',
      symbol: 'tsp',
      name: 'teaspoon',
      aliases: ['tsp.', 'us teaspoon', 'us teaspoons'],
      factor: US_GALLON / 768,
      system: 'us',
    },
    {
      id: 'tbsp',
      symbol: 'tbsp',
      name: 'tablespoon',
      aliases: ['tbsp.', 'tbs', 'tbs.', 'us tablespoon', 'us tablespoons'],
      factor: US_GALLON / 256,
      system: 'us',
    },
    {
      id: 'tsp-metric',
      symbol: 'metric tsp',
      name: 'metric teaspoon',
      factor: 0.000_005,
      system: 'metric',
    },
    {
      id: 'tbsp-metric',
      symbol: 'metric tbsp',
      name: 'metric tablespoon',
      factor: 0.000_015,
      system: 'metric',
    },
    {
      id: 'floz',
      symbol: 'fl oz',
      name: 'fluid ounce',
      // 'oz' family listed here too so kind-context lookups ("12 oz" in a
      // volume field) resolve to fluid ounces; mass wins default priority.
      aliases: [
        'fl. oz.',
        'fl-oz',
        'oz fl',
        'us fluid ounce',
        'us fluid ounces',
        'oz',
        'oz.',
        'ounce',
        'ounces',
      ],
      factor: US_GALLON / 128,
      system: 'us',
      intl: 'fluid-ounce',
      best: 0,
    },
    {
      id: 'floz-imp',
      symbol: 'imp fl oz',
      name: 'imperial fluid ounce',
      aliases: ['imp fl oz', 'imp. fl. oz.'],
      factor: 0.000_028_413_062_5,
      system: 'imperial',
    },
    {
      id: 'floz-food',
      symbol: 'food fl oz',
      name: 'nutrition fluid ounce',
      aliases: ['nutrition fl oz', 'nutrition fluid ounces', 'food fl oz'],
      factor: 0.000_03,
      system: 'us',
    },
    {
      id: 'cup',
      symbol: 'cup',
      name: 'cup',
      aliases: ['us cup', 'us cups'],
      factor: US_GALLON / 16,
      system: 'us',
      best: 1,
    },
    {
      id: 'cup-legal',
      symbol: 'legal cup',
      name: 'US legal cup',
      aliases: ['legal cup', 'legal cups', 'us legal cup', 'us legal cups'],
      factor: 0.000_24,
      system: 'us',
    },
    {
      id: 'cup-metric',
      symbol: 'metric cup',
      name: 'metric cup',
      factor: 0.000_25,
      system: 'metric',
    },
    {
      id: 'cup-imp',
      symbol: 'imp cup',
      name: 'imperial cup',
      aliases: ['imp cup', 'imperial cups'],
      factor: 0.000_284_130_625,
      system: 'imperial',
    },
    {
      id: 'pt',
      symbol: 'pt',
      name: 'pint',
      aliases: [
        'us pint',
        'us pints',
        'liquid pint',
        'liquid pints',
        'us liquid pint',
        'us liquid pints',
      ],
      factor: US_GALLON / 8,
      system: 'us',
      subunit: { unit: 'floz', per: 16 },
      best: 2,
    },
    {
      id: 'pt-imp',
      symbol: 'imp pt',
      name: 'imperial pint',
      aliases: ['imp pint', 'imperial pints'],
      factor: IMPERIAL_GALLON / 8,
      system: 'imperial',
    },
    {
      id: 'qt',
      symbol: 'qt',
      name: 'quart',
      aliases: [
        'us quart',
        'us quarts',
        'liquid quart',
        'liquid quarts',
        'us liquid quart',
        'us liquid quarts',
      ],
      factor: US_GALLON / 4,
      system: 'us',
      subunit: { unit: 'pt', per: 2 },
      best: 3,
    },
    {
      id: 'qt-imp',
      symbol: 'imp qt',
      name: 'imperial quart',
      aliases: ['imp quart', 'imperial quarts'],
      factor: IMPERIAL_GALLON / 4,
      system: 'imperial',
    },
    {
      id: 'gal',
      symbol: 'gal',
      name: 'gallon',
      aliases: ['gal.', 'us gallon', 'us gallons'],
      factor: US_GALLON,
      system: 'us',
      subunit: { unit: 'qt', per: 4 },
      intl: 'gallon',
      best: 4,
    },
    {
      id: 'gal-imp',
      symbol: 'imp gal',
      name: 'imperial gallon',
      aliases: ['imp gal', 'imp. gal.', 'imperial gallons'],
      factor: IMPERIAL_GALLON,
      system: 'imperial',
    },
    {
      id: 'bbl',
      symbol: 'bbl',
      name: 'oil barrel',
      aliases: ['barrel', 'barrels', 'oil bbl'],
      factor: 42 * US_GALLON,
      system: 'us',
    },
  ],
} as const)

// Deliberately no dry gallon or dry pint variants in v0.1.
