// ISO 4217 currency code → ISO 3166-1 alpha-2 country codes that use it as an
// official currency. Scoped to the currencies lingo ships (units/currency.ts).
// Primary/most-recognized issuer first. Not exhaustive for widely-adopted
// currencies (USD, EUR) — the main official users, enough to answer
// "which countries use this currency" and "what currency does this country use".
export const currencyCountries: Readonly<Record<string, readonly string[]>> = {
  USD: ['US', 'EC', 'SV', 'PA', 'TL', 'ZW'],
  EUR: [
    'AT',
    'BE',
    'HR',
    'CY',
    'EE',
    'FI',
    'FR',
    'DE',
    'GR',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MT',
    'NL',
    'PT',
    'SK',
    'SI',
    'ES',
  ],
  GBP: ['GB'],
  JPY: ['JP'],
  CHF: ['CH', 'LI'],
  CAD: ['CA'],
  AUD: ['AU', 'NR', 'TV', 'KI'],
  CNY: ['CN'],
  INR: ['IN', 'BT'],
  KRW: ['KR'],
  SGD: ['SG'],
  HKD: ['HK'],
  NZD: ['NZ', 'CK', 'NU'],
  MXN: ['MX'],
  BRL: ['BR'],
  ZAR: ['ZA', 'LS', 'NA', 'SZ'],
  SEK: ['SE'],
  NOK: ['NO'],
  DKK: ['DK', 'GL', 'FO'],
  PLN: ['PL'],
  CZK: ['CZ'],
  HUF: ['HU'],
  TRY: ['TR'],
  ILS: ['IL'],
  AED: ['AE'],
  KWD: ['KW'],
  BHD: ['BH'],
  OMR: ['OM'],
}
