'use client'

import 'katex/dist/katex.min.css'

import katex from 'katex'
import { useMemo } from 'react'

import { cn } from '@/lib/utils'

/**
 * Typeset a LaTeX expression. Loaded through `next/dynamic` by its callers, so
 * KaTeX and its stylesheet stay out of the docs route's initial chunk.
 */
export function KatexMath({
  className,
  display = true,
  tex,
}: {
  className?: string
  display?: boolean
  tex: string
}) {
  const html = useMemo(
    () =>
      katex.renderToString(tex, {
        displayMode: display,
        // `html` alone ships only the visual glyph spans, which a screen reader
        // reads as scattered characters. This pairs them with MathML and hides
        // the visual layer from the accessibility tree.
        output: 'htmlAndMathml',
        throwOnError: false,
      }),
    [tex, display],
  )

  // KaTeX's only HTML output path is a string. `throwOnError: false` makes it
  // render malformed input as visible error markup rather than raw passthrough,
  // and every `tex` here is generated by this app from a parsed lingo result.
  return (
    <span
      className={cn(display ? 'block' : 'inline-block', className)}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}

export default KatexMath
